# -*- coding: utf-8 -*-
"""pca_change

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iotn84jC1l4tHWRoTPJz9eT5cRF9pfbL
"""

import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

"""### **Calculating PCA change:**"""

def PCA_change(df, cols, n_components, prefix='PCA_', rand_seed=4):
    pca = PCA(n_components=n_components, random_state=rand_seed)

    principalComponents = pca.fit_transform(df[cols])

    principalDf = pd.DataFrame(principalComponents)

    df.drop(cols, axis=1, inplace=True)

    principalDf.rename(columns=lambda x: str(prefix)+str(x), inplace=True)

    df = pd.concat([df, principalDf], axis=1)
    
    return df